# Generated by Django 5.2.6 on 2025-09-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='lang',
            field=models.CharField(choices=[('py', 'Python'), ('js', 'JavaScript'), ('go', 'Goland'), ('cpp', 'C++'), ('html', 'HTML')], max_length=30),
        ),
    ]
